In [1]:
!pip install geopandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: geopandas in c:\users\lenovo\appdata\roaming\python\python313\site-packages (1.1.3)
Requirement already satisfied: numpy>=1.24 in c:\programdata\anaconda3\lib\site-packages (from geopandas) (2.3.5)
Requirement already satisfied: pyogrio>=0.7.2 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from geopandas) (0.12.1)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from geopandas) (25.0)
Requirement already satisfied: pandas>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from geopandas) (2.3.3)
Requirement already satisfied: pyproj>=3.5.0 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from geopandas) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from geopandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas>=2.0.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=2.0.0->geopandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas>=2.0.0->geopandas) (2025.2)
Requirement already satisfied: certifi in c:\programdata\anaconda3\lib\site-packages (from pyogrio>=0.7.2->geopandas) (2026.4.22)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas) (1.17.0)

In [2]:
import pandas as pd
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt

In [3]:
first_round = pd.read_csv("first_round_may.csv")

mail = pd.read_excel("mail_ballots.xlsx")

northgate = pd.read_csv("northgate_early_inperson.csv")

registered = pd.read_csv("registered_voters.csv")

southfield = pd.read_excel("southfield_early_inperson.xlsx")

In [4]:
import pandas as pd

first_round = pd.read_csv("first_round_may.csv")

In [5]:
first_round.head()

   voter_id             name          election   vote_date
0   7002115  Michael Johnson  2026 May General  2026-05-06
1   7002116     Jennifer Lee  2026 May General  2026-05-04
2   7006216    Yuki Martinez  2026 May General  2026-05-04
3   7002123        Jose Khan  2026 May General  2026-05-05
4   7006220   Jennifer Davis  2026 May General  2026-05-06

In [6]:
first_round.describe()

           voter_id
count  1.169000e+03
mean   7.004964e+06
std    2.926318e+03
min    7.000018e+06
25%    7.002405e+06
50%    7.004960e+06
75%    7.007447e+06
max    7.009966e+06

In [7]:
first_round.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1169 entries, 0 to 1168
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   voter_id   1169 non-null   int64
 1   name       1169 non-null   object
 2   election   1169 non-null   object
 3   vote_date  1169 non-null   object
dtypes: int64(1), object(3)
memory usage: 36.7+ KB

In [8]:
first_round['vote_date'] = pd.to_datetime(first_round['vote_date'])

In [9]:
first_round.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1169 entries, 0 to 1168
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   voter_id   1169 non-null   int64
 1   name       1169 non-null   object
 2   election   1169 non-null   object
 3   vote_date  1169 non-null   datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 36.7+ KB

In [10]:
first_round['voter_id'] = first_round['voter_id'].astype(str)

In [11]:
first_round.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1169 entries, 0 to 1168
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   voter_id   1169 non-null   object
 1   name       1169 non-null   object
 2   election   1169 non-null   object
 3   vote_date  1169 non-null   datetime64[ns]
dtypes: datetime64[ns](1), object(3)
memory usage: 36.7+ KB

In [12]:
first_round.head()

  voter_id             name          election  vote_date
0  7002115  Michael Johnson  2026 May General 2026-05-06
1  7002116     Jennifer Lee  2026 May General 2026-05-04
2  7006216    Yuki Martinez  2026 May General 2026-05-04
3  7002123        Jose Khan  2026 May General 2026-05-05
4  7006220   Jennifer Davis  2026 May General 2026-05-06

In [13]:
first_round['vote_date'].head()

0   2026-05-06
1   2026-05-04
2   2026-05-04
3   2026-05-05
4   2026-05-06
Name: vote_date, dtype: datetime64[ns]

In [14]:
first_round.duplicated().sum()

np.int64(0)

In [15]:
first_round.isnull().sum()

voter_id     0
name         0
election     0
vote_date    0
dtype: int64

In [16]:
import pandas as pd
mail = pd.read_excel("mail_ballots.xlsx")

In [17]:
mail.head()

      VUID            Voter   City State Return Date
0  7004160   Linda Anderson  LAKESIDE TX  2026-06-02
1  7004800         Liam Lee  LAKESIDE TX  2026-06-02
2  7007233  Elizabeth Rossi  LAKESIDE TX  2026-06-01
3  7007748   Emma Hernandez  LAKESIDE TX  2026-06-02
4  7003783        Mei Singh  LAKESIDE TX  2026-06-02

In [18]:
mail.describe()

               VUID
count  7.400000e+01
mean   7.004516e+06
std    2.739010e+03
min    7.000127e+06
25%    7.002249e+06
50%    7.004720e+06
75%    7.006111e+06
max    7.009966e+06

In [19]:
mail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   VUID         74 non-null     int64
 1   Voter        74 non-null     object
 2   City State   74 non-null     object
 3   Return Date  74 non-null     object
dtypes: int64(1), object(3)
memory usage: 2.4+ KB

In [20]:
mail["Return Date"] = pd.to_datetime(mail["Return Date"])

In [21]:
mail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   VUID         74 non-null     int64
 1   Voter        74 non-null     object
 2   City State   74 non-null     object
 3   Return Date  74 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 2.4+ KB

In [22]:
mail["VUID"] = mail["VUID"].astype(str)

In [23]:
mail["Voter"] = mail["Voter"].astype("string")

In [24]:
mail["City State"] = mail["City State"].astype("string")

In [25]:
mail["City State"] = mail["City State"].astype("category")

In [26]:
mail["Return Date"].head()

0   2026-06-02
1   2026-06-02
2   2026-06-01
3   2026-06-02
4   2026-06-02
Name: Return Date, dtype: datetime64[ns]

In [27]:
mail["City State"].nunique()

1

In [28]:
mail.sort_values("Return Date")

       VUID           Voter   City State Return Date
36  7001666      John Patel  LAKESIDE TX  2026-06-01
45  7009110     Liam Mensah  LAKESIDE TX  2026-06-01
46  7002328     Linda Cohen  LAKESIDE TX  2026-06-01
38  7000388  Priya Anderson  LAKESIDE TX  2026-06-01
47  7002331       Sofia Lee  LAKESIDE TX  2026-06-01
..      ...             ...          ...         ...
37  7005635      David Wang  LAKESIDE TX  2026-06-02
39  7000130      Omar Smith  LAKESIDE TX  2026-06-02
40  7003076  Michael Garcia  LAKESIDE TX  2026-06-02
42  7006672      John Smith  LAKESIDE TX  2026-06-02
73  7005280      John Rossi  LAKESIDE TX  2026-06-02

[74 rows x 4 columns]

In [29]:

mail[mail["Return Date"] >= "2026-06-01"]

       VUID            Voter   City State Return Date
0   7004160   Linda Anderson  LAKESIDE TX  2026-06-02
1   7004800         Liam Lee  LAKESIDE TX  2026-06-02
2   7007233  Elizabeth Rossi  LAKESIDE TX  2026-06-01
3   7007748   Emma Hernandez  LAKESIDE TX  2026-06-02
4   7003783        Mei Singh  LAKESIDE TX  2026-06-02
..      ...              ...          ...         ...
69  7000127   Jennifer Rossi  LAKESIDE TX  2026-06-01
70  7006100     James Nguyen  LAKESIDE TX  2026-06-01
71  7008479    Robert Wilson  LAKESIDE TX  2026-06-01
72  7002045      David Patel  LAKESIDE TX  2026-06-02
73  7005280       John Rossi  LAKESIDE TX  2026-06-02

[74 rows x 4 columns]

In [30]:
mail["Return Date"].dt.month

0     6
1     6
2     6
3     6
4     6
     ..
69    6
70    6
71    6
72    6
73    6
Name: Return Date, Length: 74, dtype: int32

In [31]:
mail["Return Date"] = pd.to_datetime(mail["Return Date"])

In [32]:
mail.head()

      VUID            Voter   City State Return Date
0  7004160   Linda Anderson  LAKESIDE TX  2026-06-02
1  7004800         Liam Lee  LAKESIDE TX  2026-06-02
2  7007233  Elizabeth Rossi  LAKESIDE TX  2026-06-01
3  7007748   Emma Hernandez  LAKESIDE TX  2026-06-02
4  7003783        Mei Singh  LAKESIDE TX  2026-06-02

In [33]:
mail.duplicated().sum()

np.int64(5)

In [34]:
mail.isnull().sum()

VUID           0
Voter          0
City State     0
Return Date    0
dtype: int64

In [35]:
import pandas as pd
northgate = pd.read_csv("northgate_early_inperson.csv")

In [36]:
northgate.head()

   CertificateNumber            VoterName    VoterAddress    VoteDate
0            7004160      Anderson, Linda   4728 Cedar Ln  2026-06-03
1            7007236       Park, Patricia  3840 Aspen Way  2026-06-04
2            7008259        Anderson, Mei    1071 Pine Ct  2026-06-01
3            7000076  Hernandez, Patricia   6690 Aspen Ln  06/03/2026
4            7009804     Hernandez, James    721 Aspen Ct  2026-06-02

In [37]:
northgate.describe()

       CertificateNumber
count       1.230000e+02
mean        7.005091e+06
std         2.962892e+03
min         7.000076e+06
25%         7.002546e+06
50%         7.005314e+06
75%         7.007484e+06
max         7.009921e+06

In [38]:
northgate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CertificateNumber  123 non-null    int64
 1   VoterName          123 non-null    object
 2   VoterAddress       123 non-null    object
 3   VoteDate           123 non-null    object
dtypes: int64(1), object(3)
memory usage: 4.0+ KB

In [39]:

northgate["VoteDate"] = pd.to_datetime(northgate["VoteDate"], errors="coerce")
northgate["VoterName"] = northgate["VoterName"].astype("string")
northgate["VoterAddress"] = northgate["VoterAddress"].astype("string")

In [40]:
northgate["CertificateNumber"] = northgate["CertificateNumber"].astype("string")

In [41]:
northgate["VoteDate"].dt.month
northgate["VoteDate"].dt.year
northgate.sort_values("VoteDate")

    CertificateNumber        VoterName       VoterAddress   VoteDate
39            7008429      Davis, Hana       9418 Elm Way 2026-06-01
93            7006602      Brown, Hana    7228 Birch Blvd 2026-06-01
51            7009491     Brown, James      5357 Cedar Ct 2026-06-01
87            7006063  Smith, Patricia    308 Hawthorn St 2026-06-01
56            7004400    Okafor, James   749 Dogwood Blvd 2026-06-01
..                ...              ...                ...        ...
108           7004599      Cohen, Kofi        9955 Oak St        NaT
113           7007172    Nguyen, Aisha       2063 Pine Ct        NaT
115           7008718     Thomas, Omar  1276 Sycamore Way        NaT
119           7006705    Thomas, Aisha   6880 Cypress Way        NaT
120           7008242       Ali, Linda      976 Aspen Trl        NaT

[123 rows x 4 columns]

In [42]:
northgate["VoterAddress"] = northgate["VoterAddress"].astype("category")

In [43]:
northgate.head()

  CertificateNumber            VoterName    VoterAddress   VoteDate
0           7004160      Anderson, Linda   4728 Cedar Ln 2026-06-03
1           7007236       Park, Patricia  3840 Aspen Way 2026-06-04
2           7008259        Anderson, Mei    1071 Pine Ct 2026-06-01
3           7000076  Hernandez, Patricia   6690 Aspen Ln        NaT
4           7009804     Hernandez, James    721 Aspen Ct 2026-06-02

In [44]:
northgate.duplicated().sum()

np.int64(0)

In [45]:
northgate.isnull().sum()

CertificateNumber     0
VoterName             0
VoterAddress          0
VoteDate             26
dtype: int64

In [46]:
import pandas as pd

northgate["VoteDate"] = pd.to_datetime(
    northgate["VoteDate"],
    errors="coerce")

In [47]:
northgate.isnull().sum()

CertificateNumber     0
VoterName             0
VoterAddress          0
VoteDate             26
dtype: int64

In [48]:
northgate[northgate["VoteDate"].isna()]

    CertificateNumber            VoterName       VoterAddress VoteDate
3             7000076  Hernandez, Patricia      6690 Aspen Ln      NaT
6             7002140         Cohen, Linda       100 Birch Ln      NaT
7             7001632        Smith, Carlos     8493 Willow Dr      NaT
9             7009827         Brown, Maria  7730 Magnolia Trl      NaT
13            7009836        Park, Michael        172 Oak Trl      NaT
18            7000130          Smith, Omar    768 Magnolia Ln      NaT
26            7000184  Hernandez, Patricia    5343 Cypress St      NaT
28            7009921        Thomas, Maria  3003 Juniper Blvd      NaT
29            7005314           Brown, Ama     3817 Willow Ct      NaT
31            7001224       Anderson, Kofi    5476 Juniper Ln      NaT
32            7008394        Johnson, Liam        1614 Elm Ct      NaT
44            7006400        Smith, Robert   5539 Sycamore Ln      NaT
46            7004870         Nguyen, John    9631 Dogwood Ln      NaT
48            7007433         Nguyen, Kofi     6216 Maple Trl      NaT
52            7006425          Davis, Noah  5929 Dogwood Blvd      NaT
86            7008620       Johnson, David       5256 Elm Way      NaT
91            7006080         Cohen, Sofia      9771 Birch Ct      NaT
95            7002001         Davis, Linda        4436 Elm St      NaT
103           7006106       Hernandez, Wei        545 Oak Way      NaT
105           7006639         Wang, Olivia   5934 Magnolia Ct      NaT
106           7001008          Garcia, Mei    931 Sycamore St      NaT
108           7004599          Cohen, Kofi        9955 Oak St      NaT
113           7007172        Nguyen, Aisha       2063 Pine Ct      NaT
115           7008718         Thomas, Omar  1276 Sycamore Way      NaT
119           7006705        Thomas, Aisha   6880 Cypress Way      NaT
120           7008242           Ali, Linda      976 Aspen Trl      NaT

In [49]:
northgate = northgate.dropna(subset=["VoteDate"])

In [50]:
northgate.isnull().sum()

CertificateNumber    0
VoterName            0
VoterAddress         0
VoteDate             0
dtype: int64

In [51]:
northgate.info()

<class 'pandas.core.frame.DataFrame'>
Index: 97 entries, 0 to 122
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CertificateNumber  97 non-null     string
 1   VoterName          97 non-null     string
 2   VoterAddress       97 non-null     category
 3   VoteDate           97 non-null     datetime64[ns]
dtypes: category(1), datetime64[ns](1), string(2)
memory usage: 8.2 KB

In [52]:
northgate["Month"] = northgate["VoteDate"].dt.month
northgate["Year"] = northgate["VoteDate"].dt.year
northgate["Day"] = northgate["VoteDate"].dt.day

In [53]:
northgate.head()

,CertificateNumber,VoterName,VoterAddress,VoteDate,Month,Year,Day
0,7004160,"Anderson, Linda",4728 Cedar Ln,2026-06-03,6,2026,3
1,7007236,"Park, Patricia",3840 Aspen Way,2026-06-04,6,2026,4
2,7008259,"Anderson, Mei",1071 Pine Ct,2026-06-01,6,2026,1
4,7009804,"Hernandez, James",721 Aspen Ct,2026-06-02,6,2026,2
5,7002643,"Singh, Patricia",4862 Dogwood Way,2026-06-02,6,2026,2

In [54]:
import pandas as pd

registered = pd.read_csv("registered_voters.csv")

In [55]:
registered.head()

,SOS_VoterID,firstname,lastname,streetnumber,streetname,address,city,county,precinct_raw,party,sex,age,subdivision
0,7005758,Emma,Okafor,4545,Juniper St,4545 Juniper St,Lakeside,Southfield,15,DEM,M,55.0,NaN
1,7003258,Yuki,Nguyen,7348,Dogwood Dr,7348 Dogwood Dr,LAKESIDE,Northgate,10,NPA,M,35.0,STONEBRIAR SEC 7 (CPL)
2,7007413,Priya,Wilson,4387,Cypress Dr,4387 Cypress Dr,LAKESIDE,Northgate,20,U,F,24.0,STONEBRIAR SECTION 4
3,7006220,Jennifer,Davis,7152,Cypress Dr,7152 Cypress Dr,LAKESIDE,Southfield,15,LIB,M,29.0,OAK HOLLOW UNIT 5
4,7009799,David,Ali,5091,Juniper St,5091 Juniper St,LAKESIDE,Northgate,110,Independent,M,32.0,WILLOW CREEK PH 3

In [56]:
registered.describe()

        SOS_VoterID  streetnumber  precinct_raw          age
count  4.012000e+03   4012.000000   4012.000000  3871.000000
mean   7.004970e+06   5030.946411     84.371635    54.734694
std    2.865438e+03   2857.758045     83.216507    23.186685
min    7.000002e+06    100.000000     10.000000     0.000000
25%    7.002492e+06   2526.250000     20.000000    35.000000
50%    7.004954e+06   5089.000000     45.000000    54.000000
75%    7.007436e+06   7418.750000    130.000000    74.000000
max    7.009966e+06   9998.000000    264.000000   150.000000

In [57]:
registered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4012 entries, 0 to 4011
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   SOS_VoterID   4012 non-null   int64
 1   firstname     4012 non-null   object
 2   lastname      4012 non-null   object
 3   streetnumber  4012 non-null   int64
 4   streetname    4012 non-null   object
 5   address       4012 non-null   object
 6   city          4012 non-null   object
 7   county        4012 non-null   object
 8   precinct_raw  4012 non-null   int64
 9   party         3715 non-null   object
 10  sex           3351 non-null   object
 11  age           3871 non-null   float64
 12  subdivision   3211 non-null   object
dtypes: float64(1), int64(3), object(9)
memory usage: 407.6+ KB

In [58]:
registered.isnull().sum()

SOS_VoterID       0
firstname         0
lastname          0
streetnumber      0
streetname        0
address           0
city              0
county            0
precinct_raw      0
party           297
sex             661
age             141
subdivision     801
dtype: int64

In [59]:
registered['party'] = registered['party'].fillna('Unknown')
registered['sex'] = registered['sex'].fillna('Unknown')
registered['subdivision'] = registered['subdivision'].fillna('Unknown')

In [60]:
registered['age'] = registered['age'].fillna(registered['age'].median())

In [61]:
registered['age'] = registered['age'].astype(int)

In [62]:
cat_cols = ['city', 'county', 'party', 'sex', 'subdivision']

for col in cat_cols:
    registered[col] = registered[col].astype('category')

In [63]:
registered['sex'] = registered['sex'].str.upper()

In [64]:
registered['sex'] = registered['sex'].replace({
    'MALE': 'M',
    'FEMALE': 'F'
})

In [3]:
import pandas as pd

registered = pd.read_csv("registered_voters.csv")

In [4]:
print(registered.columns)

Index(['SOS_VoterID', 'firstname', 'lastname', 'streetnumber', 'streetname',
       'address', 'city', 'county', 'precinct_raw', 'party', 'sex', 'age',
       'subdivision'],
      dtype='object')

In [5]:
registered['address'] = (
    registered['streetnumber'].astype(str) + " " +
    registered['streetname'] + ", " +
    registered['city'])

In [66]:
registered = registered.drop(['streetnumber', 'streetname'], axis=1)

In [67]:
registered = registered.drop_duplicates()

In [68]:
registered.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4000 entries, 0 to 4011
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   SOS_VoterID   4000 non-null   int64
 1   firstname     4000 non-null   object
 2   lastname      4000 non-null   object
 3   address       4000 non-null   object
 4   city          4000 non-null   category
 5   county        4000 non-null   category
 6   precinct_raw  4000 non-null   int64
 7   party         4000 non-null   category
 8   sex           4000 non-null   object
 9   age           4000 non-null   int64
 10  subdivision   4000 non-null   category
dtypes: category(4), int64(3), object(4)
memory usage: 267.1+ KB

In [69]:
registered.head()

,SOS_VoterID,firstname,lastname,address,city,county,precinct_raw,party,sex,age,subdivision
0,7005758,Emma,Okafor,4545 Juniper St,Lakeside,Southfield,15,DEM,M,55,Unknown
1,7003258,Yuki,Nguyen,7348 Dogwood Dr,LAKESIDE,Northgate,10,NPA,M,35,STONEBRIAR SEC 7 (CPL)
2,7007413,Priya,Wilson,4387 Cypress Dr,LAKESIDE,Northgate,20,U,F,24,STONEBRIAR SECTION 4
3,7006220,Jennifer,Davis,7152 Cypress Dr,LAKESIDE,Southfield,15,LIB,M,29,OAK HOLLOW UNIT 5
4,7009799,David,Ali,5091 Juniper St,LAKESIDE,Northgate,110,Independent,M,32,WILLOW CREEK PH 3

In [70]:
import pandas as pd
southfield = pd.read_excel("southfield_early_inperson.xlsx")

In [71]:
southfield.head()

  Total records: 97       Unnamed: 1 Unnamed: 2  Unnamed: 3
0        voter_guid             name       Muni  date_voted
1           7003136        Wei Brown   LAKESIDE  2026-06-03
2           7002115  Michael Johnson   LAKESIDE  2026-06-03
3           7007748   Emma Hernandez   LAKESIDE  2026-06-02
4           7003143     Carlos Singh   LAKESIDE  2026-06-01

In [72]:
southfield.describe()

       Total records: 97  Unnamed: 1 Unnamed: 2  Unnamed: 3
count                 98          98         98          98
unique                98          92          2           5
top           voter_guid  Aisha Khan   LAKESIDE  2026-06-04
freq                   1           2         97          28

In [73]:
southfield.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98 entries, 0 to 97
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Total records: 97  98 non-null     object
 1   Unnamed: 1         98 non-null     object
 2   Unnamed: 2         98 non-null     object
 3   Unnamed: 3         98 non-null     object
dtypes: object(4)
memory usage: 3.2+ KB

In [74]:
southfield.columns = southfield.iloc[0]
southfield = southfield[1:]

In [75]:
southfield = southfield.reset_index(drop=True)

In [76]:
southfield['voter_guid'] = pd.to_numeric(southfield['voter_guid'], errors='coerce')

In [77]:
southfield['date_voted'] = pd.to_datetime(southfield['date_voted'], errors='coerce')

In [78]:
southfield['Muni'] = southfield['Muni'].astype('category')

In [79]:
southfield = southfield.drop_duplicates()

In [80]:
southfield.head()

0  voter_guid                name      Muni date_voted
0     7003136           Wei Brown  LAKESIDE 2026-06-03
1     7002115     Michael Johnson  LAKESIDE 2026-06-03
2     7007748      Emma Hernandez  LAKESIDE 2026-06-02
3     7003143        Carlos Singh  LAKESIDE 2026-06-01
4     7000080  Patricia Rodriguez  LAKESIDE 2026-06-04

In [81]:
southfield.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   voter_guid  97 non-null     int64
 1   name        97 non-null     object
 2   Muni        97 non-null     category
 3   date_voted  97 non-null     datetime64[ns]
dtypes: category(1), datetime64[ns](1), int64(1), object(1)
memory usage: 2.6+ KB

In [82]:
southfield.isnull().sum()

0
voter_guid    0
name          0
Muni          0
date_voted    0
dtype: int64

In [84]:

for name, df in {
    "registered": registered,
    "northgate": northgate,
    "southfield": southfield,
    "mail": mail,
    "first_round": first_round
}.items():
    print(f"\n{name.upper()}")
    print(df.head())
    print(df.columns)
    print(df.info())

REGISTERED
   SOS_VoterID firstname lastname          address      city      county  \
0      7005758      Emma   Okafor  4545 Juniper St  Lakeside  Southfield
1      7003258      Yuki   Nguyen  7348 Dogwood Dr  LAKESIDE   Northgate
2      7007413     Priya   Wilson  4387 Cypress Dr  LAKESIDE   Northgate
3      7006220  Jennifer    Davis  7152 Cypress Dr  LAKESIDE  Southfield
4      7009799     David      Ali  5091 Juniper St  LAKESIDE   Northgate

   precinct_raw        party sex  age             subdivision
0            15          DEM   M   55                 Unknown
1            10          NPA   M   35  STONEBRIAR SEC 7 (CPL)
2            20            U   F   24    STONEBRIAR SECTION 4
3            15          LIB   M   29       OAK HOLLOW UNIT 5
4           110  Independent   M   32       WILLOW CREEK PH 3
Index(['SOS_VoterID', 'firstname', 'lastname', 'address', 'city', 'county',
       'precinct_raw', 'party', 'sex', 'age', 'subdivision'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
Index: 4000 entries, 0 to 4011
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   SOS_VoterID   4000 non-null   int64
 1   firstname     4000 non-null   object
 2   lastname      4000 non-null   object
 3   address       4000 non-null   object
 4   city          4000 non-null   category
 5   county        4000 non-null   category
 6   precinct_raw  4000 non-null   int64
 7   party         4000 non-null   category
 8   sex           4000 non-null   object
 9   age           4000 non-null   int64
 10  subdivision   4000 non-null   category
dtypes: category(4), int64(3), object(4)
memory usage: 267.1+ KB
None

NORTHGATE
  CertificateNumber         VoterName      VoterAddress   VoteDate  Month  \
0           7004160   Anderson, Linda     4728 Cedar Ln 2026-06-03      6
1           7007236    Park, Patricia    3840 Aspen Way 2026-06-04      6
2           7008259     Anderson, Mei      1071 Pine Ct 2026-06-01      6
4           7009804  Hernandez, James      721 Aspen Ct 2026-06-02      6
5           7002643   Singh, Patricia  4862 Dogwood Way 2026-06-02      6

   Year  Day
0  2026    3
1  2026    4
2  2026    1
4  2026    2
5  2026    2
Index(['CertificateNumber', 'VoterName', 'VoterAddress', 'VoteDate', 'Month',
       'Year', 'Day'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
Index: 97 entries, 0 to 122
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CertificateNumber  97 non-null     string
 1   VoterName          97 non-null     string
 2   VoterAddress       97 non-null     category
 3   VoteDate           97 non-null     datetime64[ns]
 4   Month              97 non-null     int32
 5   Year               97 non-null     int32
 6   Day                97 non-null     int32
dtypes: category(1), datetime64[ns](1), int32(3), string(2)
memory usage: 9.3 KB
None

SOUTHFIELD
0  voter_guid                name      Muni date_voted
0     7003136           Wei Brown  LAKESIDE 2026-06-03
1     7002115     Michael Johnson  LAKESIDE 2026-06-03
2     7007748      Emma Hernandez  LAKESIDE 2026-06-02
3     7003143        Carlos Singh  LAKESIDE 2026-06-01
4     7000080  Patricia Rodriguez  LAKESIDE 2026-06-04
Index(['voter_guid', 'name', 'Muni', 'date_voted'], dtype='object', name=0)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   voter_guid  97 non-null     int64
 1   name        97 non-null     object
 2   Muni        97 non-null     category
 3   date_voted  97 non-null     datetime64[ns]
dtypes: category(1), datetime64[ns](1), int64(1), object(1)
memory usage: 2.6+ KB
None

MAIL
      VUID            Voter   City State Return Date
0  7004160   Linda Anderson  LAKESIDE TX  2026-06-02
1  7004800         Liam Lee  LAKESIDE TX  2026-06-02
2  7007233  Elizabeth Rossi  LAKESIDE TX  2026-06-01
3  7007748   Emma Hernandez  LAKESIDE TX  2026-06-02
4  7003783        Mei Singh  LAKESIDE TX  2026-06-02
Index(['VUID', 'Voter', 'City State', 'Return Date'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   VUID         74 non-null     object
 1   Voter        74 non-null     string
 2   City State   74 non-null     category
 3   Return Date  74 non-null     datetime64[ns]
dtypes: category(1), datetime64[ns](1), object(1), string(1)
memory usage: 2.0+ KB
None

FIRST_ROUND
  voter_id             name          election  vote_date
0  7002115  Michael Johnson  2026 May General 2026-05-06
1  7002116     Jennifer Lee  2026 May General 2026-05-04
2  7006216    Yuki Martinez  2026 May General 2026-05-04
3  7002123        Jose Khan  2026 May General 2026-05-05
4  7006220   Jennifer Davis  2026 May General 2026-05-06
Index(['voter_id', 'name', 'election', 'vote_date'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1169 entries, 0 to 1168
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   voter_id   1169 non-null   object
 1   name       1169 non-null   object
 2   election   1169 non-null   object
 3   vote_date  1169 non-null   datetime64[ns]
dtypes: datetime64[ns](1), object(3)
memory usage: 36.7+ KB
None

In [99]:
southfield = southfield.rename(columns={
    "vote_guid": "certificateNumber",
    "date_voted": "vote_date"})

In [95]:
print(northgate.columns.tolist())
print(southfield.columns.tolist())
print(registered.columns.tolist())

['CertificateNumber', 'VoterName', 'VoterAddress', 'VoteDate', 'Month', 'Year', 'Day']
['voter_guid', 'name', 'Muni', 'vote_date']
['SOS_VoterID', 'firstname', 'lastname', 'address', 'city', 'county', 'precinct_raw', 'party', 'sex', 'age', 'subdivision']

In [92]:
northgate = northgate.rename(columns={"CertificateNumber": "CertificateNumber"})

In [97]:
northgate["CertificateNumber"] = northgate["CertificateNumber"].astype(str)
southfield["voter_guid"] = southfield["voter_guid"].astype(str)
registered["SOS_VoterID"] = registered["SOS_VoterID"].astype(str)

In [98]:
northgate = northgate.drop_duplicates(subset="CertificateNumber")
southfield = southfield.drop_duplicates(subset="voter_guid")

In [103]:
northgate = northgate.rename(columns={"CertificateNumber": "voter_id"})
southfield = southfield.rename(columns={"voter_guid": "voter_id"})
registered = registered.rename(columns={"SOS_VoterID": "voter_id"})

In [104]:
northgate["voter_id"] = northgate["voter_id"].astype(str)
southfield["voter_id"] = southfield["voter_id"].astype(str)
registered["voter_id"] = registered["voter_id"].astype(str)

In [105]:
early_votes = pd.concat(
    [northgate, southfield],
    ignore_index=True
)

early_votes = early_votes.drop_duplicates(subset="voter_id")

In [7]:
mail = pd.read_excel("mail_ballots.xlsx")

In [8]:
mail["VUID"] = mail["VUID"].astype(str)

accepted_mail = mail.copy()

In [11]:
northgate = pd.read_csv("northgate_early_inperson.csv")

In [14]:
southfield = pd.read_excel("southfield_early_inperson.xlsx")

_IncompleteInputError: incomplete input (815710527.py, line 1)

In [2]:
mail_voters = set(accepted_mail["VUID"])

northgate_voters = set(northgate["CertificateNumber"].astype(str))
southfield_voters = set(southfield["voter guid"].astype(str))

runoff_voters = mail_voters | northgate_voters | southfield_voters

NameError: name 'accepted_mail' is not defined

In [16]:
print("Mail Voters:", mail["VUID"].nunique())
print("Total mail records:", len(mail))

Mail Voters: 69
Total mail records: 74

In [17]:
print(northgate.columns.tolist())
print(southfield.columns.tolist())
print(registered.columns.tolist())

['CertificateNumber', 'VoterName', 'VoterAddress', 'VoteDate']
['Total records: 97', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']
['SOS_VoterID', 'firstname', 'lastname', 'streetnumber', 'streetname', 'address', 'city', 'county', 'precinct_raw', 'party', 'sex', 'age', 'subdivision']

In [20]:
import pandas as pd

northgate = pd.read_csv("northgate_early_inperson.csv")
southfield = pd.read_csv("southfield_early_inperson.xlxs")

FileNotFoundError: [Errno 2] No such file or directory: 'southfield_early_inperson.xlxs'

In [21]:
print(northgate.columns.tolist())
print(southfield.columns.tolist())

['CertificateNumber', 'VoterName', 'VoterAddress', 'VoteDate']
['Total records: 97', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']

In [30]:
northgate = northgate.rename(columns={'CertificateNumber': 'voter_id'})
southfield = southfield.rename(columns={'voter_guid': 'voter_id'})

early_votes = pd.concat([
    northgate[['voter_id']],
    southfield[['voter_id']]
], ignore_index=True)

KeyError: "None of [Index(['voter_id'], dtype='object')] are in the [columns]"

In [31]:
print(southfield.columns.tolist())

['Total records: 97', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']

In [36]:

registered_voters = registered_voters.merge(
    registered,
    left_on="voter_id",
    right_on="SOS_VoterID",
    how="inner")

NameError: name 'registered_voters' is not defined